---

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  changed_when: true
  notify:
    - nginx restart

- name: Include remove default
  include_tasks: remove-defaults.yml

- name: Include configure
  include_tasks: configure.yml
