---
- name: Initial Setup
  hosts: node-1
  remote_user: root

  tasks:    
     - name: Add SSH key for root
       lineinfile:
         path: ~/.ssh/authorized_keys
         create: yes
         state: present
         # line: 
     
     - name: Install Language package fr
       apt:
         name: language-pack-fr
         state: present

     - name: Ensure the locale exists
       locale_gen:
         name: fr_FR.UTF-8
         state: present
         
     - name: Set fr_FR.UTF-8 as default locale
       lineinfile:
         path: /etc/default/locale
         create: yes
         state: present
         line: LC_ALL=fr_FR.UTF-8
     
     - name: Update all packages
       apt:
          update_cache: yes
          name: '*'
          force_apt_get: yes
          state: latest
       when: ansible_facts['os_family'] == 'Debian' # ansible_facts are data related to remote system
      
     - name: Install some basic packages
       package:
          name: "{{packages}}"
          state: present
       vars:
          packages:
             - gcc
             - make
             - build-essential
             - dos2unix
             - wget
             - unzip
             - git
             - git-lfs #  manages large files with Git.
             - mcrypt # crypting program
             - libmcrypt4 # implements all the algorithms and modes found in mcrypt
             - libpcre3-dev 
             - libpng-dev # reads and writes PNG format files
             - chrony #  implements of the Network Time Protocol (NTP)
             - re2c # generates fast lexers which outputs for parser input
             - unattended-upgrades # install software updated, including security updates
             - whois
             - vim
             - pv # allows us for the monitoring of data being sent through pipe
             - bash-completion
             - net-tools #  includes the important tools for controlling the network subsystem
             - procps # provides command-line and full-screen mode utilities for navigating procfs
             - jq # is like sed for JSON data, useful to slice, filter and map and transform structured data
