---
- name: Initial Setup
  hosts: node-1
  remote_user: root

  tasks:    
     - name: Add SSH key for root
       lineinfile:
         path: ~/.ssh/authorized_keys
         create: yes
         state: present
         line:  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtI2iRY5yhqFFtQNgNozkjYg9xdI4YACzzcJeh+0kLojH/efl+TYg8t/WufN9Ux8tJrGx1r/ZTKoOR/cv21brypXQccQdSIzCag+IHX7NvFQsKsyer7aD6oqJ+mWMyjJzwhkt1Je3awjGrQ9ETcffxELi40Mreqz6cipEBjN31Pkjy8te1N3D5u83kJGWOO4g51t0IR3GLpz6Q+bmAMcSWBteJ6yjb2oBCgIbz/r/EZUG/+2UKiDbYclNiT5/ePHU8cmU7CwwNm7TxAYjYQE/6w6WsC9CCPzIGD24dYUXx9P8Fuh8xxqmtxMlSqVavv8gHvjVPObnUdNDtDx0y8eybWxKZUDRBWEpRlDyCCCfTEnjOzR2vgepKw1v426RsvL+HtGhZobU8CPLPJtYHhoNl1vpkviQbDxJNnymTAT8qCZ8SZ6l0xSjQzu2lfk75DbrZdOn46WJbByWE5PbPRlq7kHylUtyd3XZo5W44MhBhc/xgmSOfu42UuB9EXKPZBGM= sahamada@DESKTOP-K8G045V
     
     - name: Install Language package fr
       apt:
         name: language-pack-fr
         state: present

    #  - name: Ensure the locale exists
    #    locale_gen:
    #      name: fr_FR.UTF-8
    #      state: present
         
     - name: Set fr_FR.UTF-8 as default locale
       lineinfile:
         path: /etc/default/locale
         create: yes
         state: present
         line: LC_ALL=fr_FR.UTF-8
     
     - name: Update all packages
       apt:
          update_cache: yes
          name: '*'
          force_apt_get: yes
          state: latest
       when: ansible_facts['os_family'] == 'Debian' # ansible_facts are data related to remote system
      
     - name: Install some basic packages
       package:
          name: "{{packages}}"
          state: present
       vars:
          packages:
             - gcc
             - make
             - build-essential
             - dos2unix
             - wget
             - unzip
             - git
             - git-lfs #  manages large files with Git.
             - mcrypt # crypting program
             - libmcrypt4 # implements all the algorithms and modes found in mcrypt
             - libpcre3-dev 
             - libpng-dev # reads and writes PNG format files
             - chrony #  implements of the Network Time Protocol (NTP)
             - re2c # generates fast lexers which outputs for parser input
             - unattended-upgrades # install software updated, including security updates
             - whois
             - vim
             - pv # allows us for the monitoring of data being sent through pipe
             - bash-completion
             - net-tools #  includes the important tools for controlling the network subsystem
             - procps # provides command-line and full-screen mode utilities for navigating procfs
             - jq # is like sed for JSON data, useful to slice, filter and map and transform structured data
