---
- name: Uninstall Nginx
  hosts: all
  remote_user: root
  tasks:
    - name: "Stop Nginx service"
      service:
        name: nginx
        state: stopped

    - name: "Remove Nginx package" 
      apt:
        name: nginx
        state: absent

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
