---

- name: "The main PPA for supported PHP versions with many PECL extensions"
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"

- name: "Update the repo"
  ansible.builtin.package:
    update_cache: true

- name: "Install generic package"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    force: true
  with_items:
    - "php-imagick"
    - "php-memcached"
    - "php-redis"
    - "php-xdebug"
    - "php-dev"

- name: "Install php{{ version }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
    force: true
  with_items:
    - "php{{ version }}-fpm"
    - "php{{ version }}-mysql"
    - "php{{ version }}-bcmath"
    - "php{{ version }}-bz2"
    - "php{{ version }}-cli"
    - "php{{ version }}-common"
    - "php{{ version }}-curl"
    - "php{{ version }}-dba"
    - "php{{ version }}-dev"
    - "php{{ version }}-enchant"
    - "php{{ version }}-gd"
    - "php{{ version }}-gmp"
    - "php{{ version }}-imap"
    - "php{{ version }}-intl"
    - "php{{ version }}-ldap"
    - "php{{ version }}-mbstring"
    - "php{{ version }}-mysql"
    - "php{{ version }}-opcache"
    - "php{{ version }}-pgsql"
    - "php{{ version }}-phpdbg"
    - "php{{ version }}-pspell"
    - "php{{ version }}-readline"
    - "php{{ version }}-snmp"
    - "php{{ version }}-soap"
    - "php{{ version }}-sqlite3"
    - "php{{ version }}-tidy"
    - "php{{ version }}-xml"
    - "php{{ version }}-xmlrpc"
    - "php{{ version }}-xsl"
    - "php{{ version }}-zip"

- name: "Select php{{ version }} as default alternatives"
  community.general.alternatives:
    name: "{{ item.key }}"
    path: "{{ item.value }}"
  with_dict: "{{ symbolic_links }}"

- name: "[cli] Set php.ini common directive"
  ansible.builtin.lineinfile:
    dest: "/etc/php/{{ version }}/cli/php.ini"
    regexp: "{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ directives.cli }}"

- name: "[fpm] Set php.ini commmon directive"
  ansible.builtin.lineinfile:
    dest: /etc/php/{{ version }}/fpm/php.ini
    regexp: "{{ item.key }} ="
    line: "{{ item.key }} = {{ item.values }}"
  with_dict: "{{ directives.fpm }}"

- name: "[fpm] Set php.ini openssl directive"
  ansible.builtin.blockinfile:
    path: /etc/php/{{ version }}/fpm/php.ini
    block: |
      [openssl]
      openssl.cainfo = /etc/ssl/certs/ca-certificates.crt
      [curl]
      curl.cainfo = /etc/ssl/certs/ca-certificates.crt

- name: "[fpm] Setup module X-Debug"
  ansible.builtin.blockinfile:
    path: /etc/php/{{ version }}/mods-available/xdebug.ini
    block: |
      xdebug.remote_enable = 1
      xdebug.remote_connect_back = 1
      xdebug.remote_port = 9000
      xdebug.max_nesting_level = 512

- name: "[fpm] Setup module opcache"
  ansible.builtin.lineinfile:
    path: /etc/php/{{ version }}/fpm/php.ini
    line: "opcache.revalidate_freq = 0"

- name: "Include configure task"
  include_tasks: configure.yml
