---

- name: Install python packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pip
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
      - python-is-python3
